version: '2'

services:
  proxy:
    image: traefik:latest
    container_name: proxy
    networks:
      - frontend
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

networks:
  frontend:
    external:
      name: frontend
