debug = false
checkNewVersion = true
logLevel = "INFO"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "huberm.mywire.org"
watch = true
exposedbydefault = false


[acme]
email = "micah.huber@mailbox.org"
storage = "acme.json"
entryPoint = "https"
onDemand = true
onHostRule = true
acmeLogging = true
